title = "Hugo: A Fast and Flexible Website Generator"
baseurl = "https://bwaycer.github.io/"
MetaDataFormat = "yaml"
pluralizeListTitles = false
enableGitInfo = true
relativeURLs = true

[blackfriday]
  plainIDAnchors = true

[params]
  description = "Documentation of Hugo, a fast and flexible static site generator built with love by spf13, bep and friends in Go"
  author = "Steve Francia (spf13) and friends"
  release = "0.19"

[taxonomies]
  tag = "tags"
  group = "groups"

[[menu.main]]
    name = "下載雨果"
    pre = "<i class='fa fa-download'></i>"
    url = "https://github.com/spf13/hugo/releases"
    weight = -200
[[menu.main]]
    name = "網站展示"
    pre = "<i class='fa fa-cubes'></i>"
    url = "/showcase/"
    weight = -180
[[menu.main]]
    name = "Theme Showcase"
    pre = "<i class='fa fa-puzzle-piece'></i>"
    url = "http://themes.gohugo.io"
    weight = -170
[[menu.main]]
    name = "新聞及文章"
    pre = "<i class='fa fa-bullhorn'></i>"
    url = "/community/press/"
    weight = -160
[[menu.main]]
    name = "討論雨果"
    pre = "<i class='fa fa-comments'></i>"
    url = "http://discuss.gohugo.io/"
    weight = -150
[[menu.main]]
    name = "關於雨果"
    identifier = "about"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
[[menu.main]]
    name = "開始"
    identifier = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
[[menu.main]]
    name = "內容"
    identifier = "content"
    pre = "<i class='fa fa-file-text'></i>"
    weight = -90
[[menu.main]]
    name = "主題"
    identifier = "themes"
    pre = "<i class='fa fa-desktop'></i>"
    weight = -85
[[menu.main]]
    parent = "themes"
    name = "Theme Showcase"
    url = "http://themes.gohugo.io"
    weight = -170
[[menu.main]]
    name = "模板"
    identifier = "layout"
    pre = "<i class='fa fa-columns'></i>"
    weight = -80
[[menu.main]]
    name = "分類"
    identifier = "taxonomy"
    pre = "<i class='fa fa-tags'></i>"
    weight = -70
[[menu.main]]
    name = "額外"
    identifier = "extras"
    pre = "<i class='fa fa-gift'></i>"
    weight = -60
[[menu.main]]
    name = "社區"
    identifier = "community"
    pre = "<i class='fa fa-group'></i>"
    weight = -50
[[menu.main]]
    parent = "community"
    name = "Discussion Forum"
    url = "http://discuss.gohugo.io"
    weight = 150
[[menu.main]]
    name = "教程"
    identifier = "tutorials"
    pre = "<i class='fa fa-book'></i>"
    weight = -40
[[menu.main]]
    name = "故障排除"
    identifier = "troubleshooting"
    pre = "<i class='fa fa-wrench'></i>"
    weight = -30
[[menu.main]]
    name = "工具"
    url = "/tools/"
    pre = "<i class='fa fa-cogs'></i>"
    weight = -25
[[menu.main]]
    name = "雨果命令參考"
    identifier = "commands"
    pre = "<i class='fa fa-space-shuttle'></i>"
    weight = -20
    url = "/commands/"
